# rulebooks/sqs_rulebook.yml
---
- name: run_task_listener
  hosts: localhost
  sources:
    - name: hcp tf
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: fire_for_every_message
      condition: event is defined
      action:
        run_job_template:
          name: terraform process job
          organization: Default          