# sqs_rulebook.yml
---
- name: sqs_listener
  hosts: localhost          # keep it; harmless
  sources:
    - ansible.eda.aws_sqs_queue:
        name: terraform-events
        region: us-east-1
        wait_time_seconds: 20
  rules:
    - name: fire_for_every_message
      condition: event.body is defined
      action:
        run_playbook:
          name: ../playbooks/process_message.yml
          inventory: ../inventories/localhost.yml     # <-- new line
          extra_vars:
            payload: "{{ event.body }}"

