# rulebooks/sqs_rulebook.yml
---
- name: sqs_listener
  hosts: localhost
  sources:
    - ansible.eda.aws_sqs_queue:
        name: terraform-events
        region: us-east-1
        wait_time_seconds: 20
  rules:
    - name: dump env
      condition: true
      action:
        debug:
          msg: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    - name: fire_for_every_message
      condition: event.body is defined
      action:
        run_job_template:
          name: terraform process job          # exact template name
          organization: Default          # your org name
          extra_vars:
            payload: "{{ event.body }}"