# rulebooks/sqs_rulebook.yml
---
- name: run_task_listener
  hosts: localhost
  # sources:
  #   - ansible.eda.aws_sqs_queue:
  #       name: terraform-runs
  #       region: us-east-1
  #       access_key: "{{ AWS_ACCESS_KEY_ID }}"
  #       secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
  #       wait_time_seconds: 20
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: fire_for_every_message
      condition: event.body is defined
      action:
        run_job_template:
          name: terraform process job
          organization: Default          