# process_message.yml
---
# - name: Display incoming SQS event
#   hosts: localhost
#   gather_facts: false

  # vars:
  #   # ansible_eda.event.body is a JSON string like '{"ip":"1.2.3.4","user":"ec2-user"}'
  #   target_ip:   "{{ ansible_eda.event.body.ip }}"

  # tasks:
  #   - name: Debug parsed event
  #     debug:
  #       var: target_ip

  #   - name: Add dynamic host to inventory
  #     ansible.builtin.add_host:
  #       name: "{{ target_ip }}"
  #       ansible_host: "{{ target_ip }}"
  #       groups: dynamic_hosts

- name: Configure webserver on EC2 instance
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Enable nginx in amazon-linux-extras (only needed for Amazon Linux)
      ansible.builtin.command: amazon-linux-extras enable nginx1
      when: ansible_facts['distribution'] == "Amazon"

    - name: Install nginx
      ansible.builtin.package:
        name: nginx
        state: present

    - name: Start and enable nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

    - name: Create a simple web page
      ansible.builtin.copy:
        dest: /usr/share/nginx/html/index.html
        content: |
          <html>
          <head><title>Configured by Ansible</title></head>
          <body><h1>Success! This server was configured by Ansible.</h1></body>
          </html>
