# process_message.yml
---
- name: Display incoming SQS event
  hosts: localhost
  gather_facts: false        # keep it lightweight

  vars:
    raw_event:   "{{ ansible_eda.event.body }}"

  tasks:
    - name: Show raw message
      debug:
        msg: "RAW SQS payload: {{ raw_event }}"
