# process_message.yml
---
- name: Display incoming SQS event
  hosts: localhost
  gather_facts: false

  vars:
    # ansible_eda.event.body is a JSON string like '{"ip":"1.2.3.4","user":"ec2-user"}'
    raw_body:   "{{ ansible_eda.event.body }}"
    event_data: "{{ raw_body  | from_json }}"
    target_ip:  "{{ event_data.ip }}"

  tasks:
    - name: Debug parsed event
      debug:
        var: event_data
