# process_message.yml
---
- name: Display incoming SQS event
  hosts: localhost
  gather_facts: false

  vars:
    # ansible_eda.event.body is a JSON string like '{"ip":"1.2.3.4","user":"ec2-user"}'
    target_ip:   "{{ ansible_eda.event.body.ip }}"


  tasks:
    - name: Debug parsed event
      debug:
        var: target_ip
