# process_message.yml
---
- name: Display incoming SQS event
  hosts: localhost
  gather_facts: false

  # vars:
  #   # ansible_eda.event.body is a JSON string like '{"ip":"1.2.3.4","user":"ec2-user"}'
  #   target_ip:   "{{ ansible_eda.event.body.ip }}"

  # tasks:
  #   - name: Debug parsed event
  #     debug:
  #       var: target_ip

  #   - name: Add dynamic host to inventory
  #     ansible.builtin.add_host:
  #       name: "{{ target_ip }}"
  #       ansible_host: "{{ target_ip }}"
  #       groups: dynamic_hosts

- name: Connect to the newly added host
  hosts: aws hosts
  gather_facts: false

  tasks:
    - name: Test connectivity with ping
      ping:

    - name: Run a remote command
      ansible.builtin.shell: uptime
      register: uptime_out

    - name: Show uptime result
      debug:
        var: uptime_out.stdout